//https://bitdefenders.cvjd.me/web/index.html

use anyhow::Context;
use futures_util::{SinkExt, StreamExt};
use tokio_tungstenite::{connect_async, tungstenite::Message};

const CENTER_X: i32 = 24;
const CENTER_Y: i32 = 44;

const GRID_WIDTH: usize = 17;
const GRID_HEIGHT: usize = 30;

mod protocol;
use protocol::*;

mod grid;
use grid::*;

mod hero;
use hero::*;


async fn send_command<
    S: SinkExt<Message, Error = tokio_tungstenite::tungstenite::Error> + Unpin,
>(
    write: &mut S,
    msg: WebSocketMessage,
) -> anyhow::Result<()> {
    let msg_deserialized = serde_json::to_string(&msg).context("serialize message")?;
    write
        .send(Message::Text(msg_deserialized.into()))
        .await
        .context("send message")?;
    Ok(())
}



#[tokio::main]
async fn main() {
    let url = "wss://bitdefenders.cvjd.me/ws";
    let (ws, _) = connect_async(url).await.unwrap();
    let (mut write, mut read) = ws.split();

    println!("connected");
    let mut my_id: Option<i32> = None;

    let mut grid: Grid = Grid::new(GRID_WIDTH, GRID_HEIGHT);

    while let Some(msg) = read.next().await {
        let msg = msg.unwrap();

        let text = match msg {
            Message::Text(text) => text,
            Message::Ping(payload) => {
                write.send(Message::Pong(payload)).await.unwrap();
                continue;
            }
            Message::Pong(_) => {
                println!("pong");
                continue;
            }
            Message::Binary(_) => {
                println!("binary message ignored");
                continue;
            }
            Message::Close(frame) => {
                println!("closed: {frame:?}");
                break;
            }
            Message::Frame(_) => continue,
        };

        
        let message: WebSocketMessage = serde_json::from_str(text.as_ref()).unwrap();
        println!("{message:?}");

        match message.command {
            Command::Hello => {
                // Send login
                if let Err(e) = send_command(
                    &mut write,
                    WebSocketMessage {
                        command: Command::Login,
                        args: serde_json::json!({"version": 1, "name": "Andrei"}),
                    },
                )
                .await {
                    println!("Failed to send login command: {e}");
                    break;
                }
            }
            Command::Login => {
                panic!("What are you doing here?");
            }
            Command::Error => {
                println!("Error: {message:?}");
                break;
            }
            Command::Ready => {
                println!("You are ready to play!");

                if let Err(e) = send_command(
                    &mut write,
                    WebSocketMessage {
                        command: Command::Practice,
                        args: serde_json::json!({}), //seed is generated by the server by default
                    },
                )
                .await {
                    println!("Failed to send practice command: {e}");
                    break;
                }
            }
            Command::Practice => {
                println!("Something went wrong, server should not send practice command");
            }
            Command::Challenge => {
                println!("Something went wrong, server should not send challenge command");
            }
            Command::StartMatch => {
                println!("Match started!");
                let start_args: StartMatchArgs = serde_json::from_value(message.args).unwrap();
                my_id = Some(start_args.your_player_id);
            }
            Command::StartTurn => {
                println!("Your turn!");
                let turn_args: StartTurnArgs = serde_json::from_value(message.args).unwrap();
                
                grid.update_grid(&turn_args.state.heroes, &turn_args.state.walls);
                grid.print_grid();

                if let Some(my_id) = my_id {
                    for hero in turn_args.state.heroes.iter() {
                        println!("Hero {} at position ({}, {})", hero.id, hero.x, hero.y);
                        if hero.owner_id == my_id {
                            println!("This is your hero!");

                            let (new_x, new_y) = Hero_s::new(hero).hero_logic(&grid);

                            //If there are no enemy heroes, move towards the center of the map
                            if turn_args.state.heroes.iter().all(|hero| hero.owner_id == my_id) {
                                if let Err(e) = send_command(
                                    &mut write,
                                    WebSocketMessage {
                                        command: Command::Move,
                                        args: serde_json::to_value(MoveArgs {
                                            hero_id: hero.id,
                                            x: new_x,
                                            y: new_y,
                                        }).unwrap(),
                                    },
                                ).await {
                                    println!("Failed to send move command: {e}");
                                    return;
                                }
                            } else {
                                //Shoot the closest enemy hero
                                let mut closest_enemy: Option<&Hero> = None;
                                let mut min_distance = f32::INFINITY;

                                for other_hero in &turn_args.state.heroes {
                                    if other_hero.owner_id != my_id && other_hero.owner_id != hero.owner_id {
                                        let dist = (((other_hero.x - hero.x).pow(2) + (other_hero.y - hero.y).pow(2)) as f32).sqrt();
                                        if dist < min_distance {
                                            closest_enemy = Some(other_hero);
                                            min_distance = dist;
                                        }
                                    }
                                }

                                if let Some(enemy) = closest_enemy {
                                    // Shoot towards enemy position
                                    if let Err(e) = send_command(&mut write, WebSocketMessage {
                                        command: Command::Shoot,
                                        args: serde_json::to_value(ShootArgs {
                                            hero_id: hero.id,
                                            x: enemy.x,
                                            y: enemy.y,
                                        }).unwrap(),
                                    }).await {
                                        println!("Failed to send shoot command: {e}");
                                        return;
                                    }
                                }
                            }
                        }
                    }
                } else {
                    println!("Player id not set yet.");
                }

            }
            Command::Move => {
                println!("Something went wrong, server should not send move command");
            }
            Command::Shoot => {
                println!("Something went wrong, server should not send shoot command");
            }
            Command::EndMatch => {
                println!("Match ended!");
                if let Err(e) = write.send(Message::Close(None)).await {
                    println!("Failed to send close frame: {e}");
                }
                break;
            }
        }
    }
}