//https://bitdefenders.cvjd.me/web/index.html

use anyhow::Context;
use futures_util::{SinkExt, StreamExt};
use tokio_tungstenite::{connect_async, tungstenite::Message};

const GRID_WIDTH: usize = 17;
const GRID_HEIGHT: usize = 30;

// Center of the logical grid in world coordinates
// Computed as: cell_coord * 3 + 1 for middle cells
// Middle X: (17-1)/2 = 8 → 8*3+1 = 25
// Middle Y: (30-1)/2 = 14 → 14*3+1 = 43
const CENTER_X: i32 = 25;
const CENTER_Y: i32 = 43;

mod protocol;
use protocol::*;

mod grid;
use grid::*;

mod hero;
use hero::*;
use std::collections::HashMap;

use clap::{Parser, ValueEnum};


#[derive(Clone, Copy, Debug, Default, ValueEnum)]
enum Mode {
    #[default]
    Practice,
    Challenge,
}

#[derive(Debug, Clone, Parser)]
#[command(name = "demo-client")]
struct CliConfig {
    /// WebSocket URL (overrides env `WS_URL` when set on the command line).
    #[arg(long = "url", env = "WS_URL", default_value = "ws://127.0.0.1:8000/ws")]
    ws_url: String,
    /// Display name (env: `PLAYER_NAME`).
    #[arg(short, long, env = "PLAYER_NAME", default_value = "rust_demo")]
    name: String,
    #[arg(short = 'm', long, value_enum, default_value_t = Mode::Practice)]
    mode: Mode,
    #[arg(long)]
    seed: Option<u32>,
    /// Practice: player slot 0 or 1 (spawn side). Ignored in challenge mode.
    #[arg(long, default_value_t = 0, value_parser = parse_my_id)]
    my_id: i32,
    #[arg(long = "target", visible_alias = "challenge-target")]
    challenge_target: Option<String>,
    /// Challenge: queue for ranked matchmaking (ignored in practice).
    #[arg(long)]
    ranked: bool,
    /// How many matches to play before exit.
    #[arg(long, default_value_t = 1)]
    matches: u32,
}

fn parse_my_id(s: &str) -> Result<i32, String> {
    let n: i32 = s
        .parse()
        .map_err(|_| format!("`{s}`: not a valid integer"))?;
    if n == 0 || n == 1 {
        Ok(n)
    } else {
        Err("must be 0 or 1".into())
    }
}



async fn send_command<
    S: SinkExt<Message, Error = tokio_tungstenite::tungstenite::Error> + Unpin,
>(
    write: &mut S,
    msg: WebSocketMessage,
) -> anyhow::Result<()> {
    let msg_deserialized = serde_json::to_string(&msg).context("serialize message")?;
    write
        .send(Message::Text(msg_deserialized.into()))
        .await
        .context("send message")?;
    Ok(())
}



#[tokio::main]
async fn main() {
    let cfg = CliConfig::parse();
    let url = "wss://bitdefenders.cvjd.me/ws";
    let (ws, _) = connect_async(url).await.unwrap();
    let (mut write, mut read) = ws.split();

    println!("connected");
    let mut my_id: Option<i32> = None;

    let mut grid: Grid = Grid::new(GRID_WIDTH, GRID_HEIGHT);
    let mut heroes_map: HashMap<i32, Hero_s> = HashMap::new();

    while let Some(msg) = read.next().await {
        let msg = msg.unwrap();

        let text = match msg {
            Message::Text(text) => text,
            Message::Ping(payload) => {
                write.send(Message::Pong(payload)).await.unwrap();
                continue;
            }
            Message::Pong(_) => {
                println!("pong");
                continue;
            }
            Message::Binary(_) => {
                println!("binary message ignored");
                continue;
            }
            Message::Close(frame) => {
                println!("closed: {frame:?}");
                break;
            }
            Message::Frame(_) => continue,
        };

        
        let message: WebSocketMessage = serde_json::from_str(text.as_ref()).unwrap();
        println!("{message:?}");

        match message.command {
            Command::Hello => {
                // Send login
                if let Err(e) = send_command(
                    &mut write,
                    WebSocketMessage {
                        command: Command::Login,
                        args: serde_json::json!({"version": 1, "name": "Andrei"}),
                    },
                )
                .await {
                    println!("Failed to send login command: {e}");
                    break;
                }
            }
            Command::Login => {
                panic!("What are you doing here?");
            }
            Command::Error => {
                println!("Error: {message:?}");
                break;
            }
            Command::Ready => {
                println!("You are ready to play!");

                let command = match cfg.mode {
                    Mode::Practice => Command::Practice,
                    Mode::Challenge => Command::Challenge,
                };

                if let Err(e) = send_command(
                    &mut write,
                    WebSocketMessage {
                        command,
                        args: serde_json::json!({"ranked" : true}), //seed is generated by the server by default
                    },
                )
                .await {
                    println!("Failed to send practice command: {e}");
                    break;
                }
            }
            Command::Practice => {
                println!("Something went wrong, server should not send practice command");
            }
            Command::Challenge => {
                println!("Something went wrong, server should not send challenge command");
            }
            Command::StartMatch => {
                println!("Match started!");
                let start_args: StartMatchArgs = serde_json::from_value(message.args).unwrap();
                my_id = Some(start_args.your_player_id);
            }
            Command::StartTurn => {
                println!("Your turn!");
                let turn_args: StartTurnArgs = serde_json::from_value(message.args).unwrap();
                
                grid.update_grid(&turn_args.state.heroes, &turn_args.state.walls);
                grid.print_grid();

                // Validate planned paths after discovering new map areas; replan if blocked.
                for hero_wrapper in heroes_map.values_mut() {
                    hero_wrapper.validate_path(&grid);
                }

                if let Some(my_id) = my_id {
                    for hero in turn_args.state.heroes.iter() {
                        println!("Hero {} at position ({}, {})", hero.id, hero.x, hero.y);
                        if hero.owner_id == my_id {
                            println!("This is your hero!");

                            // Get or create persistent hero wrapper and update canonical state
                            let entry = heroes_map.entry(hero.id).or_insert_with(|| Hero_s::new(hero));
                            entry.hero = hero.clone();

                            // If there are no enemy heroes, move toward the center using planned_moves
                            if turn_args.state.heroes.iter().all(|h| h.owner_id == my_id) {
                                // plan path if nothing planned
                                if entry.planned_moves.is_empty() {
                                    entry.plan_path_to(&grid, CENTER_X, CENTER_Y);
                                }

                                if let Some((new_x, new_y)) = entry.planned_moves.pop_front() {
                                    if let Err(e) = send_command(
                                        &mut write,
                                        WebSocketMessage {
                                            command: Command::Move,
                                            args: serde_json::to_value(MoveArgs {
                                                hero_id: hero.id,
                                                x: new_x,
                                                y: new_y,
                                                comment: Some("patrol".to_string()),
                                            }).unwrap(),
                                        },
                                    ).await {
                                        println!("Failed to send move command: {e}");
                                        return;
                                    }
                                } else {
                                    // fallback to immediate logic
                                    let (new_x, new_y) = entry.hero_logic(&grid);
                                    if let Err(e) = send_command(
                                        &mut write,
                                        WebSocketMessage {
                                            command: Command::Move,
                                            args: serde_json::to_value(MoveArgs {
                                                hero_id: hero.id,
                                                x: new_x,
                                                y: new_y,
                                                comment: Some("patrol".to_string()),
                                            }).unwrap(),
                                        },
                                    ).await {
                                        println!("Failed to send move command: {e}");
                                        return;
                                    }
                                }
                            } else {
                                // Enemy spotted: plan a retreat path and shoot while moving.
                                let mut closest_enemy: Option<&Hero> = None;
                                let mut min_distance = f32::INFINITY;

                                for other_hero in &turn_args.state.heroes {
                                    if other_hero.owner_id != my_id && other_hero.owner_id != hero.owner_id {
                                        let dist = (((other_hero.x - hero.x).pow(2) + (other_hero.y - hero.y).pow(2)) as f32).sqrt();
                                        if dist < min_distance {
                                            closest_enemy = Some(other_hero);
                                            min_distance = dist;
                                        }
                                    }
                                }

                                if let Some(enemy) = closest_enemy {
                                    let (new_x, new_y, should_shoot) = entry.plan_keep_distance_from_enemy(
                                        &grid,
                                        enemy,
                                        hero.cooldown,
                                        &turn_args.state.projectiles,
                                    );

                                    if should_shoot {
                                        let (shoot_x, shoot_y) = entry.shoot_target_beyond_enemy(&grid, enemy);
                                        if let Err(e) = send_command(&mut write, WebSocketMessage {
                                            command: Command::Shoot,
                                            args: serde_json::to_value(ShootArgs {
                                                hero_id: hero.id,
                                                x: shoot_x,
                                                y: shoot_y,
                                                comment: Some("shoot_enemy".to_string()),
                                            }).unwrap(),
                                        }).await {
                                            println!("Failed to send shoot command: {e}");
                                            return;
                                        }
                                    } else {
                                        if let Err(e) = send_command(
                                            &mut write,
                                            WebSocketMessage {
                                                command: Command::Move,
                                                args: serde_json::to_value(MoveArgs {
                                                    hero_id: hero.id,
                                                    x: new_x,
                                                    y: new_y,
                                                    comment: Some("combat_move".to_string()),
                                                }).unwrap(),
                                            },
                                        ).await {
                                            println!("Failed to send move command: {e}");
                                            return;
                                        }   
                                    }
                                }
                            }
                        }
                    }
                } else {
                    println!("Player id not set yet.");
                }

            }
            Command::Move => {
                println!("Something went wrong, server should not send move command");
            }
            Command::Shoot => {
                println!("Something went wrong, server should not send shoot command");
            }
            Command::EndMatch => {
                println!("Match ended!");
                if let Err(e) = write.send(Message::Close(None)).await {
                    println!("Failed to send close frame: {e}");
                }
                break;
            }
        }
    }
}